# AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
CONSOLE_ENABLE = no
DATA_DRIVEN_PINS = yes
ENCODER_MAP_ENABLE = no
# LTO_ENABLE = yes
MAXTOUCH_DEBUG = no
MUSIC_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = no
TAP_DANCE_ENABLE = yes
VIA_ENABLE = yes
WPM_ENABLE = yes
# VIAL_ENABLE = yes

# Custom LCD Module
include $(KEYMAP_PATH)/my_lcd/rules.mk
